/// The HTML `<input>` element
///
/// [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)
#[doc(alias = "input")]
pub struct Input {
    accept: String,
alt: String,
autocomplete: String,
checked: String,
dirname: String,
disabled: String,
form: String,
formaction: String,
formenctype: String,
formmethod: String,
formnovalidate: String,
formtarget: String,
height: String,
list: String,
max: String,
maxlength: String,
min: String,
minlength: String,
multiple: String,
name: String,
pattern: String,
placeholder: String,
readonly: String,
required: String,
size: String,
src: String,
step: String,
type_: String,
value: String,
width: String,
access_key: String,
auto_capitalize: String,
autofocus: String,
content_editable: String,
dir: String,
draggable: String,
enter_key_hint: String,
hidden: String,
inert: String,
input_mode: String,
is_: String,
item_id: String,
item_prop: String,
item_ref: String,
item_scope: String,
item_type: String,
lang: String,
nonce: String,
popover: String,
spellcheck: String,
style: String,
tab_index: String,
title: String,
translate: String,

}
