//! HTML provides a number of elements which can be used together to create forms which the user can fill out and submit to the website or application.
mod form;
pub use form::*;
mod label;
pub use label::*;
mod option;
pub use option::*;
mod fieldset;
pub use fieldset::*;
mod select;
pub use select::*;
mod button;
pub use button::*;
mod textarea;
pub use textarea::*;
mod datalist;
pub use datalist::*;
mod legend;
pub use legend::*;
mod output;
pub use output::*;
mod progress;
pub use progress::*;
mod meter;
pub use meter::*;
mod input;
pub use input::*;
mod optgroup;
pub use optgroup::*;
