/// The HTML `<textarea>` element
///
/// [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)
#[doc(alias = "textarea")]
pub struct Textarea {
    autocomplete: String,
cols: String,
dirname: String,
disabled: String,
form: String,
maxlength: String,
minlength: String,
name: String,
placeholder: String,
readonly: String,
required: String,
rows: String,
wrap: String,
access_key: String,
auto_capitalize: String,
autofocus: String,
content_editable: String,
dir: String,
draggable: String,
enter_key_hint: String,
hidden: String,
inert: String,
input_mode: String,
is_: String,
item_id: String,
item_prop: String,
item_ref: String,
item_scope: String,
item_type: String,
lang: String,
nonce: String,
popover: String,
spellcheck: String,
style: String,
tab_index: String,
title: String,
translate: String,

}
