/// The HTML `<link>` element
///
/// [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)
#[doc(alias = "link")]
pub struct Link {
    href: String,
crossorigin: String,
rel: String,
media: String,
integrity: String,
hreflang: String,
type_: String,
referrerpolicy: String,
sizes: String,
imagesrcset: String,
imagesizes: String,
as_: String,
blocking: String,
color: String,
disabled: String,
fetchpriority: String,
access_key: String,
auto_capitalize: String,
autofocus: String,
content_editable: String,
dir: String,
draggable: String,
enter_key_hint: String,
hidden: String,
inert: String,
input_mode: String,
is_: String,
item_id: String,
item_prop: String,
item_ref: String,
item_scope: String,
item_type: String,
lang: String,
nonce: String,
popover: String,
spellcheck: String,
style: String,
tab_index: String,
title: String,
translate: String,

}
