//! The elements here are used to create and handle tabular data
mod caption;
pub use caption::*;
mod col;
pub use col::*;
mod colgroup;
pub use colgroup::*;
mod table;
pub use table::*;
mod tbody;
pub use tbody::*;
mod td;
pub use td::*;
mod tfoot;
pub use tfoot::*;
mod th;
pub use th::*;
mod thead;
pub use thead::*;
mod tr;
pub use tr::*;
