/// The HTML `<img>` element
///
/// [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)
#[doc(alias = "img")]
pub struct Image {
    alt: String,
src: String,
srcset: String,
sizes: String,
crossorigin: String,
usemap: String,
ismap: String,
width: String,
height: String,
referrerpolicy: String,
decoding: String,
loading: String,
fetchpriority: String,
access_key: String,
auto_capitalize: String,
autofocus: String,
content_editable: String,
dir: String,
draggable: String,
enter_key_hint: String,
hidden: String,
inert: String,
input_mode: String,
is_: String,
item_id: String,
item_prop: String,
item_ref: String,
item_scope: String,
item_type: String,
lang: String,
nonce: String,
popover: String,
spellcheck: String,
style: String,
tab_index: String,
title: String,
translate: String,

}
