//! In addition to regular multimedia content, HTML can include a variety of other content, even if it's not always easy to interact with.
mod area;
pub use area::*;
mod audio;
pub use audio::*;
mod embed;
pub use embed::*;
mod iframe;
pub use iframe::*;
mod img;
pub use img::*;
mod map;
pub use map::*;
mod object;
pub use object::*;
mod picture;
pub use picture::*;
mod source;
pub use source::*;
mod track;
pub use track::*;
mod video;
pub use video::*;
