/// The HTML `<script>` element
///
/// [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)
#[doc(alias = "script")]
pub struct Script {
    src: String,
type_: String,
nomodule: String,
async_: String,
defer: String,
crossorigin: String,
integrity: String,
referrerpolicy: String,
blocking: String,
fetchpriority: String,
access_key: String,
auto_capitalize: String,
autofocus: String,
content_editable: String,
dir: String,
draggable: String,
enter_key_hint: String,
hidden: String,
inert: String,
input_mode: String,
is_: String,
item_id: String,
item_prop: String,
item_ref: String,
item_scope: String,
item_type: String,
lang: String,
nonce: String,
popover: String,
spellcheck: String,
style: String,
tab_index: String,
title: String,
translate: String,

}
