//! Content sectioning elements allow you to organize the document content into logical pieces
mod address;
pub use address::*;
mod article;
pub use article::*;
mod aside;
pub use aside::*;
mod body;
pub use body::*;
mod footer;
pub use footer::*;
mod h1;
pub use h1::*;
mod h2;
pub use h2::*;
mod h3;
pub use h3::*;
mod h4;
pub use h4::*;
mod h5;
pub use h5::*;
mod h6;
pub use h6::*;
mod header;
pub use header::*;
mod hgroup;
pub use hgroup::*;
mod nav;
pub use nav::*;
mod section;
pub use section::*;
